[build]
  command = "npm run build"
  publish = "dist"

# Handle redirects with custom headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' *.steipete.me; img-src 'self' data: *.steipete.me *.githubusercontent.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.steipete.me; style-src 'self' 'unsafe-inline' *.steipete.me; font-src 'self' data: fonts.gstatic.com;"
    
# Asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"