env:
  DOCKER_COMPOSE_SERVICE: 'web'
  DOCKER_IMAGE_REPOSITORY: 'pspdfkit.azurecr.io/ci/pspdfkit-website/tests'

steps:
  - label: ':docker: Build and push image'
    agents:
      docker: true
    plugins:
      - docker-login#v2.0.1:
          server: '$DOCKER_REGISTRY'
          username: '$DOCKER_REGISTRY_LOGIN'
      - docker-compose#v3.1.0:
          build: '$DOCKER_COMPOSE_SERVICE'
          image-repository: '$DOCKER_IMAGE_REPOSITORY'
          image-name: '$DOCKER_IMAGE_TAG'
          cache-from:
            - '$DOCKER_COMPOSE_SERVICE:$DOCKER_IMAGE_REPOSITORY:$DOCKER_IMAGE_TAG'
            - '$DOCKER_COMPOSE_SERVICE:$DOCKER_IMAGE_REPOSITORY:latest'

  - wait

  - label: ':docker: Build and test website'
    command: 'bin/ci'
    branches: '!master'
    agents:
      docker: true
    plugins:
      - docker-login#v2.0.1:
          server: '$DOCKER_REGISTRY'
          username: '$DOCKER_REGISTRY_LOGIN'
      - docker-compose#v3.1.0:
          run: '$DOCKER_COMPOSE_SERVICE'
