require 'rake/testtask'
require 'rspec/core/rake_task'

namespace :test do
  Rake::TestTask.new('unit') do |t|
    t.description = 'Run unit tests'
    t.libs = %w[. test helpers lib]
    t.test_files = FileList['test/**/*_test.rb']
    t.warning = false
  end

  desc 'Run system tests'
  RSpec::Core::RakeTask.new('system') do |t|
    t.pattern = 'test/system/*_test.rb'
  end

  desc 'Run all tests'
  task all: %i[unit]
end

task default: %w[test:all]
