name: Astro Build

on:
  push:
    branches: [main, astro-erudite-design]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: "20"
  ASTRO_TELEMETRY_DISABLED: "1"

jobs:
  build:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install
          npm update

      - name: Build Astro site
        run: npm run build

      - name: Check build output
        run: ls -la dist/
